data/Delimiter/backticks.yaml
data/Language/JavaScript.yaml

Added JavaScript.yaml file to the language definitions.

Add JavaScript to languages

---

data/Delimiter/rem.yaml
data/Language/TinyBasic.yaml

This adds TinyBasic to the language definitions.

TinyBasic.yaml: Add TinyBasic language

---

assets/css/coala.css
templates/Language.html.jinja2
templates/home.html.jinja2

This commit adds assets folder with css files inside
templates/Language.html.jinja2 --> Added css
templates/home.html.jinja2 --> Added css
Related to https://github.com/coala/coAST/issues/6

html files: Adds simple style

---

data/Delimiter/php_short_open_tag.yaml
data/Language/PHP.yaml

PHP.yaml: add php language

---

assets/css/coast.css
templates/Language.html.jinja2
templates/home.html.jinja2

This adds some enhancement to basic styling, includes link and table styles.

Template: add style enhancement

---

data/DataType/int16_go.yaml
data/DataType/int32_go.yaml
data/DataType/int64_go.yaml
data/DataType/int8_go.yaml
data/DataType/uint16_go.yaml
data/DataType/uint32_go.yaml
data/DataType/uint64_go.yaml
data/DataType/uint8_go.yaml
data/Language/Golang.yaml
models/DataType.yaml
models/Language.yaml

Add datatypes attribute

---

data/Language/PHP.yaml
models/Language.yaml

This adds creation date property to php language

PHP.yaml: Add CreationDate property

---

data/EnumDelimiterType/_all.yml

update: removed duplicate word 'correctly'

---

data/DataType/boolean_java.yaml
data/DataType/byte_java.yaml
data/DataType/char_java.yaml
data/DataType/int_java.yaml
data/DataType/long_java.yaml
data/DataType/short_java.yaml
data/Delimiter/java_char.yaml
data/Language/Java.yaml
models/DataType.yaml

Add Java data types

---

data/Language/Swift.yaml

Swift.yaml --> Added new language schema: swift

Swift.yaml: Adds swift schema

---

data/Delimiter/multiline_double_slash_star.yaml
data/Delimiter/triple_slash.yaml
data/Delimiter/verbatim.yaml
data/Language/CSharp.yaml

CSharp.yaml --> Added new language schema: c#. Also adds few extra delimeters needed.

CSharp.yaml: Adds csharp schema

---

data/DataType/bool_cpp.yaml
data/DataType/char_cpp.yaml
data/DataType/int_cpp.yaml
data/DataType/long_cpp.yaml
data/DataType/short_cpp.yaml
data/DataType/void_cpp.yaml
data/Language/CPlusPlus.yaml

CPlusPlus.yaml --> Added data types for cpp

CPlusPlus.yaml: Adds datatypes

---

data/Language/Pascal.yaml

Pascal.yaml --> Added new language schema: Pascal

Pascal.yaml: Adds Pascal schema

---

data/DataType/boolean_rust.yaml
data/Delimiter/doc_comment.yaml
data/Language/Rust.yaml

data/Language/Rust.yaml >> new Rust language schema + doc_comment delimeter yaml

Add rust schema

---

data/DataType/boolean_d.yaml
data/DataType/byte_d.yaml
data/DataType/char_d.yaml
data/DataType/int_d.yaml
data/DataType/long_d.yaml
data/DataType/short_d.yaml
data/Language/D.yaml

data/Language/D.yaml >> Add language schema and boolean yaml

Add d language schema

---

data/Language/Verilog.yaml

Added Verilog(SystemVerilog) as a language.
Also updated `Language.yaml` to support multiple line-continuation characters

Add language definition for verilog and update model

---

netlify.toml

Closes https://github.com/coala/coAST/issues/13

netlify.toml: Reset stdout

---

data/DataType/boolean_coffeescript.yaml
data/Delimiter/triple_hash.yaml
data/Language/CoffeeScript.yaml

Note: keywords are from https://ref.pencilcode.net/coffee/keywords.html

CoffeeScript.yaml: Add CoffeeScript language

---

data/Language/Rust.yaml

Update the rust language definition to include the creation date and the grammar file.

Update Rust language definition

---

.travis.yml
data/Language/VisualBasic.yaml

This duplicates gitmate, catching problems that GitMate misses
in files not included in the commit.
Also tidy yaml files.
Fixes https://github.com/coala/coAST/issues/73

.travis.yml: Lint files

---

data/DataType/boolean_upper_case.yaml
data/DataType/char_pascal.yaml
data/DataType/integer_pascal.yaml
data/DataType/real_pascal.yaml
data/DataType/string_pascal.yaml
data/Language/Pascal.yaml

Add Pascal datatypes
